version: '3.8'

services:
  order_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    environment:
      PYTHONWARNINGS: "ignore:Unverified HTTPS request"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./config.json:/app/code/config.json
      - ./src:/app/code/src
      - .:/app 
      
  order_db:
    image: postgres:16
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: secret
    restart: "no"
    command: [ 'postgres', '-p', '5433' ]
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders"]
      interval: 10s
      retries: 5
      start_period: 30s


  migrations:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      order_db:
        condition: service_started
    volumes:
      - ./db_dump.sql:/common/db_dump.sql
    environment:
      - DB_URL=postgresql://user:password@localhost:5433/orders_db
    command: /bin/sh -c "psql $DB_URL -f /common/db_dump.sql"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  order_db:
